steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$prj-trail/prime-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$prj-trail/prime-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'prime-app', '--image', 'gcr.io/$prj-trail/prime-app', '--region', 'us-central1', '--platform', 'managed']

images:
  - 'gcr.io/$prj-trail/prime-app'
